version: "3.8"

networks:
  microservices_network:
    driver: bridge


services:
  service-1:
    build: ./service1
    container_name: service1
    image: service1
    environment:
      SERVER_PORT: 9090
      SERVICE_B_URL: http://service2:9091
    depends_on:
      - service2
    ports:
      - "9090:9090"
    networks:
      - microservices_network

  service2:
    build: ./service2
    container_name: service2
    image: service2
    environment:
      SERVER_PORT: 9091
    ports:
      - "9091:9091"
    networks:
      - microservices_network
