apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: https://hub.docker.com/kateilievsk123/service2:latest
          ports:
            - containerPort: 9091
